stages:
  - build
  - test
  - deploy

variables:
  DOCKER_REGISTRY: gcr.io
  PROJECT_PATH: magic-project
  TF_VERSION: "1.5.7"

.auth_gcp: &auth_gcp
  before_script:
    - echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp_key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
    - gcloud config set project $GCP_PROJECT_ID

build:
  stage: build
  image: python:3.9-slim
  script:
    - cd src/api
    - pip install -r requirements.txt
    - python -m compileall .
  artifacts:
    paths:
      - src/api/
    expire_in: 1 hour

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  <<: *auth_gcp
  script:
    - cd src/api
    - docker build -t $DOCKER_REGISTRY/$GCP_PROJECT_ID/$PROJECT_PATH:$CI_COMMIT_SHA .
    - docker push $DOCKER_REGISTRY/$GCP_PROJECT_ID/$PROJECT_PATH:$CI_COMMIT_SHA
  only:
    - main
    - staging

test:
  stage: test
  image: python:3.9-slim
  script:
    - cd src/api
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest tests/ --cov=app --cov-report=term-missing
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test_integration:
  stage: test
  image: python:3.9-slim
  script:
    - cd src/api
    - pip install -r requirements.txt
    - pip install pytest requests
    - pytest tests/integration/ -v
  only:
    - main
    - staging

.deploy_template: &deploy_definition
  image:
    name: hashicorp/terraform:$TF_VERSION
    entrypoint: [""]
  <<: *auth_gcp
  script:
    - cd terraform/environments/$CI_ENVIRONMENT_NAME
    - terraform init
    - terraform validate
    - |
      terraform plan \
        -var="project_id=$GCP_PROJECT_ID" \
        -var="container_image=$DOCKER_REGISTRY/$GCP_PROJECT_ID/$PROJECT_PATH:$CI_COMMIT_SHA" \
        -out=plan.tfplan
    - terraform apply -auto-approve plan.tfplan

deploy_staging:
  stage: deploy
  <<: *deploy_definition
  environment:
    name: staging
  only:
    - staging

deploy_prod:
  stage: deploy
  <<: *deploy_definition
  environment:
    name: prod
  only:
    - main
  when: manual

cache:
  paths:
    - .terraform
    - src/api/.pytest_cache/
    - src/api/__pycache__/