# .github/workflows/destroy.yml
name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (staging/prod)'
        required: true
        type: choice
        options:
        - staging
        - prod

env:
  PROJECT_PATH: magic-project
  TF_VERSION: "1.5.7"

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
          
      - name: Terraform Init and Destroy
        run: |
          cd terraform/environments/${{ github.event.inputs.environment }}
          terraform init
          terraform destroy \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="container_image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.PROJECT_PATH }}/${{ env.PROJECT_PATH }}:${{ github.sha }}" \
            -auto-approve